# Generated by Django 4.1.2 on 2022-12-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_myorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='amount',
            field=models.IntegerField(default=100),
        ),
    ]
